---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(magrittr)
library(tidyr)
library(ggplot2)
```


```{r}
plot(cars)
```

```{r}
File1 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Agents.csv", na.strings = "")
dim(File1)
File2 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Container.csv", na.strings = "")
dim(File2)
File3 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Contract.csv", na.strings = "")
dim(File3)
File4 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Distributor.csv", na.strings = "")
dim(File4)
File5 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Goods.csv", na.strings = "")
dim(File5)
File6 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Manufacturer.csv", na.strings = "")
dim(File6)
File7 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Payment.csv", na.strings = "")
dim(File7)
File8 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/Purchase Goods.csv", na.strings = "")
dim(File8)
File9 <- read.csv("C:/Users/Jignasu Vekariya/Documents/DMA_Project/supply from.csv", na.strings = "")
dim(File9)
```


```{r}
File5[!apply(File5 == "",1, all),]

```

```{r}
frame1 <- File5 %>%  
  filter(Quantity < 50)%>%
  select(Quantity,Price)
frame1

```


```{r}
barplot(frame1$Quantity,frame1$Price,xlab = "Quantity",ylab = "price", horiz = FALSE)
```

```{r}
File8[!apply(File8 == "",1, all),]
```

```{r}
frame2 <- File8 %>%  
  filter(Tax> 7)%>%
  select(Quantity,Tax)
frame2
```

```{r}
barplot(frame2$Quantity,frame2$Tax,xlab = "Quantity",ylab = "Tax", horiz = FALSE)

```
